name: xllify Build
description: Builds Excel custom functions from .luau to .xll
author: Acornsoft UK
branding:
  icon: "package"
  color: "green"

inputs:
  xllify_version:
    description: "Version of xllify to use"
    required: false
    default: "0.5.1"
  xllify_key:
    description: "License key for xllify"
    required: false
    default: "early-adopter"
  xll_filename:
    description: "Name of the output XLL file (without extension)"
    required: false
    default: MyAddin
  addin_name:
    description: "Internal name for the add-in project"
    required: false
    default: MyAddin
  luau_scripts:
    description: "Space or newline separated list of Luau script filenames"
    required: true

outputs:
  xll_path:
    description: "Path to the built XLL file (relative to workspace)"
    value: ${{ steps.build.outputs.xll_path }}
  test_results_path:
    description: "Path to test results XML"
    value: ${{ steps.build.outputs.test_results_path }}

runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        echo "XLLIFY_KEY=${{ inputs.xllify_key }}" >> $GITHUB_ENV

    - name: Download and extract xllify distribution
      shell: bash
      run: |
        # Download and extract xllify distribution
        VERSION="${{ inputs.xllify_version }}"
        DOWNLOAD_URL="https://storage.googleapis.com/xllify-action-assets/xllify-dist-v${VERSION}-windows.zip"
        FILENAME="xllify-dist-v${VERSION}-windows.zip"
        curl -L -o "$FILENAME" "$DOWNLOAD_URL"
        unzip -q "$FILENAME" -d xllify-dist
        echo "XLLIFY_DIST_PATH=${{ github.workspace }}/xllify-dist" >> $GITHUB_ENV

    - name: xllify
      shell: bash
      run: |
        # Stamp
        echo "${{ inputs.luau_scripts }}"
        mv template.xll tools
        SCRIPTS=$(echo "${{ inputs.luau_scripts }}" | tr '\n' ' ')
        tools/xll-stamp "${{ inputs.xll_filename }}" $SCRIPTS
        echo "xll_path=${{ inputs.xll_filename }}.xll" >> $GITHUB_OUTPUT
        echo "Stamped XLL: ${{ inputs.xll_filename }}.xll"
