name: xllify Build
description: Builds Excel custom functions from .luau to .xll in under a minute
author: Acornsoft UK
branding:
  icon: "package"
  color: "green"

inputs:
  xllify_version:
    description: "Version of xllify to use"
    required: false
    default: "0.3.47"
  xllify_key:
    description: "License key for xllify"
    required: false
    default: "early-adopter"
  xll_filename:
    description: "Name of the output XLL file (without extension)"
    required: false
    default: MyAddin
  addin_name:
    description: "Internal name for the add-in project"
    required: false
    default: MyAddin
  luau_scripts:
    description: "Space or newline separated list of Luau script filenames"
    required: true

outputs:
  xll_path:
    description: "Path to the built XLL file (relative to workspace)"
    value: ${{ steps.build.outputs.xll_path }}
  test_results_path:
    description: "Path to test results XML"
    value: ${{ steps.build.outputs.test_results_path }}

runs:
  using: "composite"
  steps:
    - name: Download and extract xllify distribution
      shell: bash
      run: |
        # Download and extract xllify distribution
        VERSION="${{ inputs.xllify_version }}"
        DOWNLOAD_URL="https://storage.googleapis.com/xllify-action-assets/xllify-dist-v${VERSION}-windows.zip"
        FILENAME="xllify-dist-v${VERSION}-windows.zip"
        curl -L -o "$FILENAME" "$DOWNLOAD_URL"
        unzip -q "$FILENAME" -d xllify-dist
        echo "XLLIFY_DIST_PATH=${{ github.workspace }}/xllify-dist" >> $GITHUB_ENV

    - name: Set up environment
      shell: bash
      run: |
        echo "XLLIFY_KEY=${{ inputs.xllify_key }}" >> $GITHUB_ENV

    - name: Run tests
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Check if tests directory exists and contains at least one .luau file
        if [ -d "tests" ] && [ -n "$(find tests -maxdepth 1 -name 'test_*.luau' -print -quit)" ]; then
          echo "Running tests..."
          echo "TESTS_FOUND=true" >> $GITHUB_ENV
          # Build load flags for source files
          LOAD_FLAGS=""
          # Normalize luau_scripts to handle both space and newline separated values
          SCRIPTS=$(echo "${{ inputs.luau_scripts }}" | tr '\n' ' ')
          for script in $SCRIPTS; do
            LOAD_FLAGS="$LOAD_FLAGS --load $script"
          done
          # List all test_*.luau files explicitly
          TEST_FILES=$(find tests -maxdepth 1 -name "test_*.luau" -type f | sort | tr '\n' ' ')
          "${{ github.workspace }}/xllify-dist/tools/xllify" --junit $LOAD_FLAGS test $TEST_FILES > "${{ github.workspace }}/test-results.xml"
        else
          echo "No tests directory or .luau files found in tests/, skipping tests"
          echo "TESTS_FOUND=false" >> $GITHUB_ENV
        fi

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Configure
        WORKSPACE="${{ github.workspace }}"
        WORKSPACE_UNIX="${WORKSPACE//\\//}"
        echo "WORKSPACE_UNIX=$WORKSPACE_UNIX" >> $GITHUB_ENV

        SCRIPTS="${{ inputs.luau_scripts }}"
        SCRIPT_PATHS=""
        for script in $SCRIPTS; do
          SCRIPT_PATHS="$SCRIPT_PATHS    $WORKSPACE_UNIX/$script"$'\n'
        done

        # Create CMakeLists.txt with provided parameters
        cat > CMakeLists.txt << 'EOF'
        cmake_minimum_required(VERSION 3.16)
        project(${{ inputs.addin_name }} VERSION 1.0.0 LANGUAGES CXX C)
        EOF

        cat >> CMakeLists.txt << EOF
        # Set the path to the xllify distribution
        set(CMAKE_PREFIX_PATH "${WORKSPACE_UNIX}/xllify-dist")
        EOF

        cat >> CMakeLists.txt << 'EOF'
        # Find the xllify package
        find_package(Xllify REQUIRED)

        # Add your Luau scripts
        xllify_add_scripts(
        EOF

        # Add script paths
        echo "$SCRIPT_PATHS" >> CMakeLists.txt

        # Complete the CMakeLists.txt
        cat >> CMakeLists.txt << 'EOF'
        )

        # Build the Excel add-in (XLL)
        xllify_build_xll(${{ inputs.xll_filename }})
        EOF

        # Create build directory
        cat CMakeLists.txt
        mkdir -p build
        cd build
        cmake ..

    - name: Build XLL
      id: build
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Build XLL
        cd build
        cmake --build . --config Release

        # Find the generated XLL file in build/Release/
        XLL_FILE=$(find . -name "${{ inputs.xll_filename }}.xll" | head -n 1)

        if [ -z "$XLL_FILE" ]; then
          echo "Error: XLL file not found"
          exit 1
        fi

        # Copy XLL to workspace root
        cp "$XLL_FILE" ../${{ inputs.xll_filename }}.xll

        # Set output path (relative to workspace)
        echo "xll_path=${{ inputs.xll_filename }}.xll" >> $GITHUB_OUTPUT
        echo "test_results_path=${{ github.workspace }}/test-results.xml" >> $GITHUB_OUTPUT

        echo "Built XLL: ${{ inputs.xll_filename }}.xll"

    - name: Clean up build directory
      shell: bash
      working-directory: ${{ github.workspace }}
      if: always()
      run: |
        # Tidy up
        rm -rf build
        rm -rf "${{ github.workspace }}/xllify-dist"
        echo "Build directory cleaned"
