name: xllify Build
description: Builds an Excel custom function add-in from .luau and .py scripts
author: xllifycom
branding:
  icon: "package"
  color: "green"

inputs:
  xllify_version:
    description: "Version of xllify distribution to use"
    required: false
    default: "0.5.2"
  xllify_key:
    description: "License key for xllify"
    required: false
    default: "early-adopter"
  xll_filename:
    description: "Name of the output XLL file (without extension)"
    required: false
    default: MyAddin
  addin_name:
    description: "Internal name for the add-in project"
    required: false
    default: MyAddin
  embed_scripts:
    description: "Space or newline separated list of .luau and/or .py script filenames"
    required: true
  python_entrypoint:
    description: "Name of Python entrypoint, will default to main.py"
    required: false

outputs:
  xll_path:
    description: "Path to the built XLL file (relative to workspace)"
    value: ${{ steps.build.outputs.xll_path }}
  test_results_path:
    description: "Path to test results XML"
    value: ${{ steps.build.outputs.test_results_path }}

runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        echo "XLLIFY_KEY=${{ inputs.xllify_key }}" >> $GITHUB_ENV

    - name: Install xllify
      shell: bash
      run: |
        # Download and extract xllify distribution
        VERSION="${{ inputs.xllify_version }}"
        DOWNLOAD_URL="https://storage.googleapis.com/xllify-action-assets/xllify-dist-v${VERSION}-windows.zip"
        FILENAME="xllify-dist-v${VERSION}-windows.zip"
        curl -L -o "$FILENAME" "$DOWNLOAD_URL"
        unzip -q "$FILENAME" -d xllify-dist
        echo "XLLIFY_DIST_PATH=${{ github.workspace }}/xllify-dist" >> $GITHUB_ENV

    - name: xllify
      id: build
      shell: bash
      run: |
        # xllify
        SCRIPTS=$(echo "${{ inputs.embed_scripts }}" | tr '\n' ' ')
        PY_ENTRYPOINT="${{ inputs.python_entrypoint }}"
        XLL_FILENAME="${{ inputs.xll_filename }}"

        # Ensure XLL_FILENAME ends with .xll
        if [[ "$XLL_FILENAME" != *.xll ]]; then
          XLL_FILENAME="${XLL_FILENAME}.xll"
        fi

        # Build xllify command with conditional --py-entrypoint flag
        # Will default to main
        if [[ "$SCRIPTS" == *".py"* && -n "$PY_ENTRYPOINT" ]]; then
          xllify-dist/xllify "$XLL_FILENAME" $SCRIPTS --py-entrypoint "$PY_ENTRYPOINT"
        else
          xllify-dist/xllify "$XLL_FILENAME" $SCRIPTS
        fi
        echo "xll_path=$XLL_FILENAME" >> $GITHUB_OUTPUT
