name: xllify build
description: Prepares and submits Luau source files to the xllify.com build API.
author: Acornsoft UK

inputs:
  xllify_key:
    description: "License key for xllify"
    required: false
    default: "early-adopter"
  xll_filename:
    description: "Name of the output XLL file (without extension)"
    required: false
    default: MyAddin
  addin_name:
    description: "Internal name for the add-in project"
    required: false
    default: MyAddin
  luau_scripts:
    description: "Space or newline separated list of Luau script filenames"
    required: true

outputs:
  xll_path:
    description: "Path to the built XLL file (relative to workspace)"
    value: ${{ steps.build.outputs.xll_path }}

runs:
  using: "composite"
  steps:
    - name: Download and extract xllify distribution
      shell: bash
      run: |
        # Download and extract xllify distribution from GitHub releases
        DOWNLOAD_URL="https://storage.googleapis.com/xllify-action-assets/xllify-dist-v1.0.9-windows.zip"
        curl -L -o xllify-dist-v1.0.9-windows.zip "$DOWNLOAD_URL"
        unzip -q xllify-dist-v1.0.9-windows.zip -d xllify-dist
        echo "XLLIFY_DIST_PATH=${{ github.workspace }}/xllify-dist" >> $GITHUB_ENV

    - name: Set up environment
      shell: bash
      run: |
        echo "XLLIFY_KEY=${{ inputs.xllify_key }}" >> $GITHUB_ENV

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Configure
        WORKSPACE="${{ github.workspace }}"
        WORKSPACE_UNIX="${WORKSPACE//\\//}"
        echo "WORKSPACE_UNIX=$WORKSPACE_UNIX" >> $GITHUB_ENV

        SCRIPTS="${{ inputs.luau_scripts }}"
        SCRIPT_PATHS=""
        for script in $SCRIPTS; do
          SCRIPT_PATHS="$SCRIPT_PATHS    \${CMAKE_SOURCE_DIR}/$script"$'\n'
        done

        # Create CMakeLists.txt with provided parameters
        cat > CMakeLists.txt << 'EOF'
        cmake_minimum_required(VERSION 3.16)
        project(${{ inputs.addin_name }} VERSION 1.0.0 LANGUAGES CXX C)
        EOF

        cat >> CMakeLists.txt << EOF
        # Set the path to the xllify distribution
        set(CMAKE_PREFIX_PATH "${WORKSPACE_UNIX}/xllify-dist")
        EOF

        cat >> CMakeLists.txt << 'EOF'
        # Find the xllify package
        find_package(Xllify REQUIRED)

        # Add your Luau scripts
        xllify_add_scripts(
        EOF

        # Add script paths
        echo "$SCRIPT_PATHS" >> CMakeLists.txt

        # Complete the CMakeLists.txt
        cat >> CMakeLists.txt << 'EOF'
        )

        # Build the Excel add-in (XLL)
        xllify_build_xll(${{ inputs.xll_filename }})
        EOF

        # Create build directory
        cat CMakeLists.txt
        mkdir -p build
        cd build
        cmake ..

    - name: Build XLL
      id: build
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Build XLL
        cd build
        cmake --build . --config Release

        # Find the generated XLL file in build/Release/
        XLL_FILE=$(find . -name "${{ inputs.xll_filename }}.xll" | head -n 1)

        if [ -z "$XLL_FILE" ]; then
          echo "Error: XLL file not found"
          exit 1
        fi

        # Copy XLL to action root
        cp "$XLL_FILE" ../${{ inputs.xll_filename }}.xll

        # Set output path (relative to workspace)
        RELATIVE_PATH="${{ github.action_path }}/${{ inputs.xll_filename }}.xll"
        # Make it relative to GITHUB_WORKSPACE
        WORKSPACE_RELATIVE=$(realpath --relative-to="${GITHUB_WORKSPACE}" "$RELATIVE_PATH" 2>/dev/null || echo "$RELATIVE_PATH")
        echo "xll_path=$WORKSPACE_RELATIVE" >> $GITHUB_OUTPUT

        echo "Built XLL: $WORKSPACE_RELATIVE"

    - name: Clean up build directory
      shell: bash
      working-directory: ${{ github.action_path }}
      if: always()
      run: |
        # Remove build directory but keep the XLL
        rm -rf build
        echo "Build directory cleaned"
