name: xllify Build
description: Builds Excel custom function add-ins from .luau and .py scripts
author: xllifycom
branding:
  icon: "package"
  color: "green"

inputs:
  xllify_version:
    description: "Version of xllify distribution to use"
    required: false
    default: "0.9.3"
  xllify_key:
    description: "License key for xllify"
    required: false
    default: "early-adopter"
  xll_filename:
    description: "Name of the output XLL file (without extension)"
    required: false
    default: MyAddin
  addin_name:
    description: "Internal name for the add-in project"
    required: false
    default: MyAddin
  embed_scripts:
    description: "Space or newline separated list of .luau and/or .py script filenames"
    required: true
  python_entrypoint:
    description: "Name of Python entrypoint, will default to main.py"
    required: false
  python_requirements:
    description: "Python requirements.txt"
    required: false

outputs:
  xll_path:
    description: "Path to the built XLL file (relative to workspace)"
    value: ${{ steps.build.outputs.xll_path }}
  test_results_path:
    description: "Path to test results XML"
    value: ${{ steps.build.outputs.test_results_path }}

runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        echo "XLLIFY_KEY=${{ inputs.xllify_key }}" >> $GITHUB_ENV
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: xllify
      id: build
      shell: bash
      run: |
        # xllify
        pip install xllify==${{ inputs.xllify_version }}
        xllify-install
        
        SCRIPTS=$(echo "${{ inputs.embed_scripts }}" | tr '\n' ' ')
        PY_ENTRYPOINT="${{ inputs.python_entrypoint }}"
        PY_REQUIREMENTS="${{ inputs.python_requirements }}"
        XLL_FILENAME="${{ inputs.xll_filename }}"


        # Ensure XLL_FILENAME ends with .xll
        if [[ "$XLL_FILENAME" != *.xll ]]; then
          XLL_FILENAME="${XLL_FILENAME}.xll"
        fi

        # Rename requirements file if provided
        if [[ -n "$PY_REQUIREMENTS" ]]; then
          mv "$PY_REQUIREMENTS" requirements.txt
        fi

        # Build xllify command
        CMD="xllify \"$XLL_FILENAME\" $SCRIPTS"

        # Add --py-entrypoint flag if provided
        if [[ "$SCRIPTS" == *".py"* && -n "$PY_ENTRYPOINT" ]]; then
          CMD="$CMD --py-entrypoint $PY_ENTRYPOINT"
        fi

        # Add --py-requirements flag if provided
        if [[ -n "$PY_REQUIREMENTS" ]]; then
          CMD="$CMD --py-requirements requirements.txt"
        fi

        # Install xllify Python package if Python scripts are included
        if [[ "$SCRIPTS" == *".py"* ]]; then
          pip install xllify==0.9.3
        fi

        eval $CMD
        echo "xll_path=$XLL_FILENAME" >> $GITHUB_OUTPUT
